"""Built-in game driver definitions.

Each driver pre-configures the full extraction pipeline for a known game.
These mirror the existing GameScheme presets + CUE4Parse EGame mappings
but add export format defaults, detection patterns, and metadata.
"""

from __future__ import annotations

from dualforge.drivers.driver import GameDriver

BUILTIN_DRIVERS = [
    GameDriver(
        name="fortnite",
        label="Fortnite",
        engine="unreal",
        game_fragments=["Fortnite", "FortniteGame"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="aes-256",
        egame="GAME_Fortnite",
        notes="Partitioned paks with OOTP and dynamic GUID keys.",
        tags=["battle-royale", "epic-games"],
        author="DualForge",
    ),
    GameDriver(
        name="delta-force",
        label="Delta Force",
        engine="unreal",
        game_fragments=["DeltaForce", "Delta Force"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="aes-256+xor8",
        egame="GAME_DeltaForce",
        notes="AES-256 followed by 8-byte repeating XOR.",
        tags=["fps", "timi-studios"],
        author="DualForge",
    ),
    GameDriver(
        name="snowbreak",
        label="Snowbreak: Containment Zone",
        engine="unreal",
        game_fragments=["Snowbreak"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="derived-aes-md5",
        egame="GAME_Snowbreak",
        notes="AES key derived from md5(pak filename).",
        tags=["tps", "seasun"],
        author="DualForge",
    ),
    GameDriver(
        name="wuthering-waves",
        label="Wuthering Waves",
        engine="unreal",
        game_fragments=["WutheringWaves", "Wuthering Waves"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="partial-encrypt",
        egame="GAME_WutheringWaves",
        notes="Partially encrypted pak (NetEase-style).",
        tags=["action-rpg", "kuro-games"],
        author="DualForge",
    ),
    GameDriver(
        name="marvel-rivals",
        label="Marvel Rivals",
        engine="unreal",
        game_fragments=["MarvelRivals", "Marvel Rivals"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="aes-256+xor8",
        egame="GAME_MarvelRivals",
        notes="AES-256 followed by 8-byte repeating XOR.",
        tags=["action", "netease"],
        author="DualForge",
    ),
    GameDriver(
        name="monster-jam",
        label="Monster Jam Showdown",
        engine="unreal",
        game_fragments=["MonsterJam", "Monster Jam"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="custom-aes-round",
        egame="GAME_MonsterJamShowdown",
        notes="Custom AES round-key engine (FIPS-197 reimplementation).",
        tags=["racing", "milestone"],
        author="DualForge",
    ),
    GameDriver(
        name="dragon-sword",
        label="Dragon Sword",
        engine="unreal",
        game_fragments=["DragonSword", "Dragon Sword"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="custom-aes-round",
        egame="GAME_DragonSword3",
        notes="Custom AES round-key engine.",
        tags=["action", "netease"],
        author="DualForge",
    ),
    GameDriver(
        name="star-savior",
        label="Star Savior",
        engine="unreal",
        game_fragments=["StarSavior", "Star Savior"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="derived-xor-md5",
        notes="Per-filename md5 XOR mask.",
        tags=["rpg"],
        author="DualForge",
    ),
    GameDriver(
        name="tekken8",
        label="Tekken 8",
        engine="unreal",
        game_fragments=["tekken", "TEKKEN"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="aes-256",
        egame="GAME_TEKKEN7",
        notes="Standard AES-256 encryption.",
        tags=["fighting", "bandai-namco"],
        author="DualForge",
    ),
    GameDriver(
        name="palworld",
        label="Palworld",
        engine="unreal",
        game_fragments=["palworld", "Palworld"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="aes-256",
        egame="GAME_Palworld",
        notes="Standard AES-256 encryption.",
        tags=["survival", "pocketpair"],
        author="DualForge",
    ),
    GameDriver(
        name="escape-from-tarkov",
        label="Escape from Tarkov",
        engine="unreal",
        game_fragments=["tarkov", "EscapeFromTarkov"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="aes-256",
        egame="GAME_EscapeFromTarkov",
        notes="Standard AES-256 encryption.",
        tags=["fps", "bstalker"],
        author="DualForge",
    ),
    GameDriver(
        name="valorant",
        label="VALORANT",
        engine="unreal",
        game_fragments=["valorant", "VALORANT"],
        archive_patterns=["pakchunk*-Windows.pak"],
        encryption_scheme="aes-256",
        egame="GAME_VALORANT",
        notes="Standard AES-256 encryption.",
        tags=["fps", "riot-games"],
        author="DualForge",
    ),
    GameDriver(
        name="generic-unity",
        label="Generic Unity Game",
        engine="unity",
        game_fragments=[],
        encryption_scheme="aes-256",
        unity_cn=False,
        export_formats={
            "Texture2D": "png",
            "Sprite": "png",
            "AudioClip": "wav",
            "Mesh": "obj",
            "TextAsset": "txt",
        },
        notes="Default driver for Unity-based games.",
        tags=["unity", "generic"],
        author="DualForge",
    ),
    GameDriver(
        name="generic-unreal",
        label="Generic Unreal Game",
        engine="unreal",
        game_fragments=[],
        encryption_scheme="aes-256",
        notes="Default driver for Unreal-based games.",
        tags=["unreal", "generic"],
        author="DualForge",
    ),
    GameDriver(
        name="unity-cn",
        label="Unity CN Pro Bundle",
        engine="unity",
        game_fragments=["unity-cn"],
        encryption_scheme="unity-cn",
        unity_cn=True,
        export_formats={
            "Texture2D": "png",
            "Sprite": "png",
            "AudioClip": "wav",
            "Mesh": "obj",
            "TextAsset": "txt",
        },
        encryption_params={"header_bytes": "0"},
        notes="Unity CN Pro 16-char bundle XOR.",
        tags=["unity", "cn"],
        author="DualForge",
    ),
]
